// Generated by CoffeeScript 2.2.1
(function() {
  var SimpleEvent;

  SimpleEvent = class SimpleEvent {
    constructor() {
      this._events = {};
    }

    bind(event, fct) {
      this._events[event] = this._events[event] || [];
      return this._events[event].push(fct);
    }

    unbind(event, fct) {
      if (!event) {
        return this._events = {};
      }
      if (!fct) {
        return delete this._events[event];
      }
      if (!this._events[event]) {
        return;
      }
      return this._events[event].splice(this._events[event].indexOf(fct), 1);
    }

    trigger(event) {
      var args;
      args = Array.prototype.slice.call(arguments, 1);
      return ['all', event].filter((ev) => {
        return !!this._events[ev];
      }).forEach((ev) => {
        return this._events[ev].forEach((fn) => {
          return fn.apply(this, ev === 'all' ? [event].concat(args) : args);
        });
      });
    }

    remove() {
      this.trigger('remove');
      return this.unbind();
    }

  };

  if (typeof module !== "undefined" && 'exports' in module) {
    module.exports = SimpleEvent;
  } else {
    window.SimpleEvent = SimpleEvent;
  }

}).call(this);
