// Generated by CoffeeScript 1.10.0
(function() {
  var SimpleEvent;

  (typeof exports !== "undefined" && exports !== null ? exports : this).SimpleEvent = SimpleEvent = (function() {
    function SimpleEvent() {}

    SimpleEvent.prototype.bind = function(event, fct) {
      if (!this._events) {
        this._events = {};
      }
      this._events[event] = this._events[event] || [];
      this._events[event].push(fct);
      return this;
    };

    SimpleEvent.prototype.unbind = function(event, fct) {
      if (!this._events) {
        return;
      }
      if (!event) {
        return this._events = {};
      }
      if (!fct) {
        return delete this._events[event];
      }
      if (!this._events[event]) {
        return;
      }
      this._events[event].splice(this._events[event].indexOf(fct), 1);
      return this;
    };

    SimpleEvent.prototype.bind_to = function(object, event, fn) {
      var fn_c;
      if (!this.__events_to) {
        this.__events_to = [];
      }
      fn_c = (function(_this) {
        return function() {
          return fn.apply(_this, arguments);
        };
      })(this);
      object[object.bind ? 'bind' : 'on'](event, fn_c);
      this.__events_to.push((function(_this) {
        return function() {
          return object[object.unbind ? 'unbind' : 'off'](event, fn_c);
        };
      })(this));
      return this;
    };

    SimpleEvent.prototype.unbind_to = function() {
      var fn;
      if (this.__events_to) {
        while (fn = this.__events_to.shift()) {
          fn();
        }
      }
      return this;
    };

    SimpleEvent.prototype.trigger = function(event) {
      var args;
      if (!this._events) {
        return;
      }
      args = Array.prototype.slice.call(arguments, 1);
      ['all', event].filter((function(_this) {
        return function(ev) {
          return !!_this._events[ev];
        };
      })(this)).forEach((function(_this) {
        return function(ev) {
          return _this._events[ev].forEach(function(fn) {
            return fn.apply(_this, ev === 'all' ? [event].concat(args) : args);
          });
        };
      })(this));
      return this;
    };

    SimpleEvent.prototype.remove = function() {
      this.trigger('remove');
      this.unbind_to();
      this.unbind();
      return this;
    };

    return SimpleEvent;

  })();

}).call(this);
